version: "3.9"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Asia/Kolkata
    volumes:
      - /opt/services/jellyfin:/config
      - /mnt/media:/media
    ports:
      - "8096:8096"
    networks:
      - media
      - edge

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      LOG_LEVEL: info
      TZ: Asia/Kolkata
    volumes:
      - /opt/services/jellyseerr:/app/config
    ports:
      - "5055:5055"
    depends_on:
      - jellyfin
    networks:
      - media
      - edge

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Asia/Kolkata
    volumes:
      - /opt/services/prowlarr:/config
    ports:
      - "9696:9696"
    networks:
      - media

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Asia/Kolkata
    volumes:
      - /opt/services/sonarr:/config
      - /mnt/media/tv:/tv
      - /mnt/downloads:/downloads
    ports:
      - "8989:8989"
    depends_on:
      - prowlarr
      - qbittorrent
    networks:
      - media

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Asia/Kolkata
    volumes:
      - /opt/services/radarr:/config
      - /mnt/media/movies:/movies
      - /mnt/downloads:/downloads
    ports:
      - "7878:7878"
    depends_on:
      - prowlarr
      - qbittorrent
    networks:
      - media

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Asia/Kolkata
      WEBUI_PORT: "8080"
    volumes:
      - /opt/services/qbittorrent:/config
      - /mnt/downloads:/downloads
    ports:
      - "8080:8080"
    networks:
      - media

networks:
  media:
    name: colossusbundi_media
  edge:
    external: true
    name: colossusbundi_edge
